We have time series data for CPU, memory, and disk usage attached in a CSV-encoded text file. We want to analyze the data to better understand what is happening so we can inform our users. Write a program that will read in the full data, bucket each series into five minute intervals (aligned to the hour), and calculate the minimum, maximum, mean, and standard deviation of the data points in each bucket. Your program should print out the calculated statistics for each bucket. Hint: Not all of the buckets will have data.

In [1]:
csv_file = r'C:\usf\Summer works\obama\timeseries.csv'

In [2]:
output_file=r'C:\usf\Summer works\obama\statistics.csv'

In [3]:
import pandas as pd
df = pd.read_csv(csv_file)

In [4]:
df

      label                      time  value
0       cpu  2018-08-01T20:05:00.000Z   0.42
1    memory  2018-08-01T20:05:00.000Z   0.50
2      disk  2018-08-01T20:05:00.000Z   0.21
3       cpu  2018-08-01T20:04:00.000Z   0.40
4    memory  2018-08-01T20:04:00.000Z   0.47
5      disk  2018-08-01T20:04:00.000Z   0.21
6       cpu  2018-08-01T20:03:00.000Z   0.81
7    memory  2018-08-01T20:03:00.000Z   0.49
8      disk  2018-08-01T20:03:00.000Z   0.22
9       cpu  2018-08-01T20:02:00.000Z   0.97
10   memory  2018-08-01T20:02:00.000Z   0.19
11     disk  2018-08-01T20:02:00.000Z   0.22
12      cpu  2018-08-01T20:01:00.000Z   0.27
13   memory  2018-08-01T20:01:00.000Z   0.64
14     disk  2018-08-01T20:01:00.000Z   0.23
15      cpu  2018-08-01T20:00:00.000Z   0.56
16   memory  2018-08-01T20:00:00.000Z   0.20
17     disk  2018-08-01T20:00:00.000Z   0.24
18      cpu  2018-08-01T19:59:00.000Z   0.01
19   memory  2018-08-01T19:59:00.000Z   0.17
20     disk  2018-08-01T19:59:00.000Z   0.24
21      cpu  2018-08-01T19:58:00.000Z   0.71
22   memory  2018-08-01T19:58:00.000Z   0.87
23     disk  2018-08-01T19:58:00.000Z   0.24
24      cpu  2018-08-01T19:57:00.000Z   0.49
25   memory  2018-08-01T19:57:00.000Z   0.90
26     disk  2018-08-01T19:57:00.000Z   0.25
27      cpu  2018-08-01T19:56:00.000Z   0.26
28   memory  2018-08-01T19:56:00.000Z   0.22
29     disk  2018-08-01T19:56:00.000Z   0.26
..      ...                       ...    ...
234     cpu  2018-08-01T18:35:00.000Z   0.88
235  memory  2018-08-01T18:35:00.000Z   0.14
236    disk  2018-08-01T18:35:00.000Z   0.68
237     cpu  2018-08-01T18:34:00.000Z   0.57
238  memory  2018-08-01T18:34:00.000Z   0.09
239    disk  2018-08-01T18:34:00.000Z   0.68
240     cpu  2018-08-01T18:33:00.000Z   0.42
241  memory  2018-08-01T18:33:00.000Z   0.04
242    disk  2018-08-01T18:33:00.000Z   0.68
243     cpu  2018-08-01T18:32:00.000Z   0.87
244  memory  2018-08-01T18:32:00.000Z   0.37
245    disk  2018-08-01T18:32:00.000Z   0.69
246     cpu  2018-08-01T18:31:00.000Z   0.83
247  memory  2018-08-01T18:31:00.000Z   0.62
248    disk  2018-08-01T18:31:00.000Z   0.70
249     cpu  2018-08-01T18:30:00.000Z   0.18
250  memory  2018-08-01T18:30:00.000Z   0.64
251    disk  2018-08-01T18:30:00.000Z   0.71
252     cpu  2018-08-01T18:29:00.000Z   0.67
253  memory  2018-08-01T18:29:00.000Z   0.05
254    disk  2018-08-01T18:29:00.000Z   0.71
255     cpu  2018-08-01T18:28:00.000Z   0.47
256  memory  2018-08-01T18:28:00.000Z   0.15
257    disk  2018-08-01T18:28:00.000Z   0.71
258     cpu  2018-08-01T18:27:00.000Z   0.10
259  memory  2018-08-01T18:27:00.000Z   0.52
260    disk  2018-08-01T18:27:00.000Z   0.72
261     cpu  2018-08-01T18:26:00.000Z   0.10
262  memory  2018-08-01T18:26:00.000Z   0.11
263    disk  2018-08-01T18:26:00.000Z   0.73

[264 rows x 3 columns]

In [5]:
df['time'] = pd.to_datetime(df['time'])
df.set_index('time', inplace=True)

In [6]:
df_cpu=df[df['label'] == 'cpu']
df_disk=df[df['label'] == 'disk']
df_memory=df[df['label'] == 'memory']

In [7]:
cpu_std=df_cpu.groupby(pd.TimeGrouper('5Min'))['value'].std().reset_index().rename(columns={'value':'cpu_std'})
cpu_mean=df_cpu.groupby(pd.TimeGrouper('5Min'))['value'].mean().reset_index().rename(columns={'value':'cpu_mean'})
cpu_min=df_cpu.groupby(pd.TimeGrouper('5Min'))['value'].min().reset_index().rename(columns={'value':'cpu_min'})
cpu_max=df_cpu.groupby(pd.TimeGrouper('5Min'))['value'].max().reset_index().rename(columns={'value':'cpu_max'})
disk_std=df_disk.groupby(pd.TimeGrouper('5Min'))['value'].std().reset_index().rename(columns={'value':'disk_std'})
disk_mean=df_disk.groupby(pd.TimeGrouper('5Min'))['value'].mean().reset_index().rename(columns={'value':'disk_mean'})
disk_min=df_disk.groupby(pd.TimeGrouper('5Min'))['value'].min().reset_index().rename(columns={'value':'disk_min'})
disk_max=df_disk.groupby(pd.TimeGrouper('5Min'))['value'].max().reset_index().rename(columns={'value':'disk_max'})
memory_std=df_memory.groupby(pd.TimeGrouper('5Min'))['value'].std().reset_index().rename(columns={'value':'memory_std'})
memory_mean=df_memory.groupby(pd.TimeGrouper('5Min'))['value'].mean().reset_index().rename(columns={'value':'memory_mean'})
memory_min=df_memory.groupby(pd.TimeGrouper('5Min'))['value'].min().reset_index().rename(columns={'value':'memory_min'})
memory_max=df_memory.groupby(pd.TimeGrouper('5Min'))['value'].max().reset_index().rename(columns={'value':'memory_max'})

In [8]:
result=pd.concat([cpu_mean.set_index('time'),cpu_max.set_index('time'),cpu_min.set_index('time'),cpu_std.set_index('time'),memory_mean.set_index('time'),memory_max.set_index('time'),memory_min.set_index('time'),memory_std.set_index('time'),disk_mean.set_index('time'),disk_max.set_index('time'),disk_min.set_index('time'),disk_std.set_index('time')], axis=1, join='inner').reset_index()

In [9]:
result

,time,cpu_mean,cpu_max,cpu_min,cpu_std,memory_mean,memory_max,memory_min,memory_std,disk_mean,disk_max,disk_min,disk_std
0,2018-08-01 18:25:00,0.335000,0.67,0.10,0.283373,0.207500,0.52,0.05,0.212348,0.717500,0.73,0.71,0.009574
1,2018-08-01 18:30:00,0.574000,0.87,0.18,0.288149,0.352000,0.64,0.04,0.283320,0.692000,0.71,0.68,0.013038
2,2018-08-01 18:35:00,0.408000,0.88,0.01,0.369554,0.494000,0.93,0.14,0.370783,0.672000,0.68,0.67,0.004472
3,2018-08-01 18:40:00,0.500000,0.88,0.19,0.285745,0.558000,0.84,0.23,0.231668,0.648000,0.66,0.64,0.008367
4,2018-08-01 18:45:00,0.522000,0.93,0.32,0.260135,0.376000,0.87,0.05,0.305090,0.628000,0.63,0.62,0.004472
5,2018-08-01 18:50:00,0.524000,0.88,0.18,0.319265,0.262000,0.47,0.12,0.132740,0.600000,0.62,0.58,0.015811
6,2018-08-01 18:55:00,0.604000,0.86,0.34,0.201321,0.318000,0.90,0.05,0.341863,0.570000,0.58,0.56,0.010000
7,2018-08-01 19:00:00,0.476000,0.94,0.05,0.421224,0.326000,0.65,0.05,0.252250,0.556000,0.56,0.55,0.005477
8,2018-08-01 19:05:00,0.476000,0.73,0.18,0.233944,0.674000,0.90,0.42,0.180222,0.528000,0.54,0.52,0.008367
9,2018-08-01 19:10:00,0.352000,0.78,0.05,0.306790,0.376000,0.98,0.05,0.421224,0.506000,0.52,0.50,0.008944
10,2018-08-01 19:15:00,0.590000,0.87,0.29,0.251496,0.346000,0.56,0.05,0.234798,0.478000,0.49,0.47,0.008367
11,2018-08-01 19:20:00,0.758000,0.91,0.52,0.187270,0.688000,0.90,0.30,0.229717,0.458000,0.47,0.44,0.013038
12,2018-08-01 19:25:00,0.524000,0.97,0.11,0.333736,0.530000,0.98,0.14,0.361248,0.418000,0.43,0.41,0.008367
13,2018-08-01 19:30:00,0.656000,1.00,0.26,0.327613,0.416000,0.80,0.14,0.245112,0.384000,0.40,0.37,0.011402
14,2018-08-01 19:35:00,0.322000,0.48,0.10,0.158019,0.724000,0.90,0.53,0.139929,0.352000,0.36,0.34,0.008367
15,2018-08-01 19:40:00,0.676667,0.94,0.47,0.240069,0.386667,0.82,0.02,0.404145,0.323333,0.33,0.32,0.005774
16,2018-08-01 19:45:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2018-08-01 19:50:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2018-08-01 19:55:00,0.416000,0.71,0.01,0.282276,0.482000,0.90,0.17,0.369148,0.250000,0.26,0.24,0.010000
19,2018-08-01 20:00:00,0.602000,0.97,0.27,0.287871,0.398000,0.64,0.19,0.196647,0.224000,0.24,0.21,0.011402
20,2018-08-01 20:05:00,0.420000,0.42,0.42,NaN,0.500000,0.50,0.50,NaN,0.210000,0.21,0.21,NaN

In [10]:
result.to_csv(output_file)